---
title: "Portfolio"
pagetitle: 'Portfolio'
output: 
  html_document: 
    css: "styles.css"
---

```{r, include=FALSE}
htmltools::tagList(rmarkdown::html_dependency_font_awesome())
```


*Check out some examples of my work below*

<br>

- <i class="fa fa-chart-line"> </i> [Project 1: 2019 and 2020 Rushing statistics](https://spksonti.github.io/project1/)

    - This was my first project for my data science class and it was an analysis on the rushing 
    leaders in the NFL from the years of 2019 and 2020. It utilized dplyr, kable, ggplot2, and tidyverse 
    to handle data wrangling, data tidying, and graph creating. Very interesting discoveries were made
    throughout the project, take a look!

<br>

- <i class="fa fa-chart-pie"> </i> [Project 2: 2019 and 2020 Rushing classifications and predictions](https://spksonti.github.io/project2)

    - This was the second project I did in my data science class and my second project on the rushing leaders
    in the NFL from the years of 2019 and 2020. It utilized linear regression and prediction, linear classification, kNN, 
    CV k-fold classification, and a bit of python with the reticulate library. I found some very interesting
    connections so if you're an NFL fan please take a look! If not, still take a look, you never know what you
    might find!
